Repository coder/docs, pull requests merged in 2021-04, with the labels that each got.

#214 chore: use the same linter settings as the monorepo
  .github/workflows/ci.yaml
  package.json
Labels: chore :wrench:

#222 Document network policy requirement [ch9751]
  setup/requirements.md
Labels: docs :memo:

#235 update GCP node type in create cluster command
  setup/kubernetes/google.md
Labels: docs :memo:

#161 add Coder capabilities doc for code-server users
  assets/jetbrains-launcher-icons.png
  assets/manage-users.png
  guides/code-server-envs.md
  guides/deployments/code-server.md
  manifest.json
Labels: docs :memo:, enhancement :sparkles:

#252 chore: Add release pr template
  .github/PULL_REQUEST_TEMPLATE/release-template.md
  .markdownlintignore
Labels: chore :wrench:

#253 chore: Print PR template link in create-clog.sh
  scripts/create-clog.sh
Labels: chore :wrench:

#256 clarify helm uninstall
  setup/updating.md
Labels: docs :memo:

#261 add link to README with helm values
  setup/installation.md
Labels: docs :memo:

#260 clarify timescale deletion
  setup/updating.md
Labels: docs :memo:

#268 fix: jetbrains image link
  admin/environment-management/installing-jetbrains.md
Labels: docs :memo:

#273 add: VNC documentation
  guides/customization/vnc.md
  manifest.json
Labels: docs :memo:

#269 add: Cloud DNS SSL config
  guides/ssl-certificates/cloudDNS.md
  guides/ssl-certificates/route53.md
  manifest.json
Labels: docs :memo:

#278 specify ECDSA use
  admin/git.md
  environments/preferences.md
Labels: docs :memo:

#284 add port table
  setup/architecture.md
Labels: docs :memo:

#299 state yaml syntax case-sensitivity
  workspaces/workspaces-as-code/templates.md
Labels: docs :memo:

#310 fix: private key command
  guides/ssl-certificates/cloudDNS.md
Labels: docs :memo:

#302 feat: connecting an external postgres
  guides/deployments/postgres.md
  manifest.json
  setup/installation.md
Labels: docs :memo:

#308 update wp commands with namespace
  admin/workspace-providers/deployment.md
Labels: docs :memo:

#311 remove optional flag & make commands consistent
  guides/admin/helm-charts.md
  setup/installation.md
  setup/updating.md
Labels: docs :memo:
