Repository coder/docs, pull requests merged in 2021-02, with the labels that each got.

#71 Replace helm command with upgrade and specify repo
  admin/devurls.md
Labels: docs :memo:

#56 1.16 changelog
  changelog/1.16.0.md
  changelog/index.md
  manifest.json
Labels: docs :memo:, enhancement :sparkles:

#114 Update @ericpaulsen as a contributor
  .all-contributorsrc
  README.md
Labels: chore :wrench:

#111 tear down
  guides/teardown.md
  manifest.json
Labels: docs :memo:
