Repository coder/docs, pull requests merged in 2021-03, with the labels that each got.

#134 keycloak
  assets/SAML-config-1.png
  assets/SAML-config-2.png
  assets/SAML-process.png
  assets/keycloak-IdP-redirector.png
  assets/keycloak-add-client.png
  assets/keycloak-authenticator-config.png
  assets/keycloak-client-config.png
  assets/keycloak-coder-config.png
  assets/keycloak-create-client.png
  assets/keycloak-default-IdP.png
  assets/keycloak-identity-providers.png
  assets/keycloak-metadata-import.png
  assets/keycloak-secret.png
  guides/keycloak.md
  manifest.json
Labels: docs :memo:

#138 chore: add doc on managing .gitconfig
  guides/gitconfig.md
  manifest.json
Labels: docs :memo:

#144 ericpaulsen/gkeupdates
  setup/kubernetes/google.md
Labels: docs :memo:

#141 ericpaulsen/gitconfig
  guides/gitconfig.md
  manifest.json
Labels: docs :memo:

#146 fix: home directory
  environments/lifecycle.md
Labels: docs :memo:

#147 Chore: Clarify updating steps to include values override
  setup/updating.md
Labels: docs :memo:

#157 external auth providers & k8s [ch8919]
  setup/kubernetes/aws.md
  setup/kubernetes/azure.md
  setup/kubernetes/google.md
Labels: docs :memo:

#165 fix: typo
  guides/gitconfig.md
Labels: docs :memo:

#177 fix: URL
  changelog/1.14.0.md
Labels: docs :memo:

#178 fix: typo & formatting
  cli/file-sync.md
  guides/mobile-development.md
Labels: docs :memo:

#200 chore: Generate clog from template
  scripts/create-clog.sh
  scripts/template_changelog.md
Labels: chore :wrench:

#201 add: cluster deploy timelines
  setup/kubernetes/aws.md
  setup/kubernetes/google.md
Labels: docs :memo:

#202 clarify supported git providers
  admin/git.md
Labels: docs :memo:

#203 clarify network policy implementations
  setup/kubernetes/azure.md
  setup/kubernetes/google.md
Labels: docs :memo:

#218 fix: README fmt
  README.md
Labels: bug :bug:, chore :wrench:

#215 chore: upgrade husky to version 6
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: chore :wrench:

#221 chore: use hash of pull request head in preview message
  .github/workflows/preview.yaml
Labels: chore :wrench:

#223 chore: Add post-checkout hook
  .husky/post-checkout
Labels: chore :wrench:

#219 Release 1.17.2
  admin/templates.md
  assets/wac-badge.png
  assets/wac-location.png
  changelog/1.17.2.md
  environments/workspaces-as-code/index.md
  environments/workspaces-as-code/templates.md
  manifest.json
Labels: release :bookmark:

#208 chore: Automate adding clog to manifest
  .prettierrc
  manifest.json
  package.json
  scripts/add_clog_to_manifest.ts
  scripts/create-clog.sh
  tsconfig.json
  yarn.lock
Labels: chore :wrench:
