Repository coder/docs, pull requests merged in 2022-09, with the labels that each got.

#1108 add: helm chart verbose toggle
  changelog/1.34.0.md
Labels: docs :memo:

#1115 fix: make env var a string
  admin/git.md
  admin/workspace-management/limits.md
Labels: bug :bug:

#1119 fix: make jupyter binary executable
  workspaces/editors.md
Labels: bug :bug:

#1066 replace sidebar icons with icon_path
  admin/index.md
  assets/images/icons/gear.svg
  assets/images/icons/get-started.svg
  assets/images/icons/guides.svg
  assets/images/icons/home.svg
  assets/images/icons/images.svg
  assets/images/icons/paper.svg
  assets/images/icons/terminal.svg
  assets/images/icons/workspaces.svg
  assets/images/icons/wrench.svg
  changelog/index.md
  cli/index.md
  getting-started/index.md
  guides/index.md
  images/index.md
  index.md
  manifest.json
  setup/index.md
  workspaces/index.md
Labels: enhancement :sparkles:
