Repository coder/docs, pull requests merged in 2022-10, with the labels that each got.

#1146 add: admin field/audit log mappings
  admin/audit.md
Labels: docs :memo:, enhancement :sparkles:

#1152 add: 1.30 db migrations note
  setup/upgrade/considerations.md
Labels: docs :memo:

#1153 chore: update air-gap setup to include code-marketplace, and remote SSH IDE with air-gap
  setup/air-gapped/index.md
  workspaces/editors.md
Labels: docs :memo:, chore :wrench:
